# Generated by Django 6.0.2 on 2026-03-21 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0003_besoin_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=200)),
                ('contenu', models.CharField(max_length=1500)),
                ('emetteur', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PP.compteadmin')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PP.projet')),
                ('receveur', models.ManyToManyField(to='PP.compteetudiant')),
            ],
        ),
    ]
