# Generated by Django 6.0.2 on 2026-03-23 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0004_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='emetteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PP.compteadmin'),
        ),
    ]
