# Generated by Django 6.0.2 on 2026-04-02 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0005_alter_message_emetteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='compteetudiant',
            name='niveau_etude',
            field=models.CharField(choices=[('1CP', 'One'), ('2CP', 'Two'), ('1CS', 'Three'), ('2CS', 'Four'), ('3CS', 'Five')], default='1CP', max_length=5),
        ),
        migrations.AlterField(
            model_name='message',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PP.projet'),
        ),
    ]
