# Generated by Django 6.0.2 on 2026-04-03 16:06

import PP.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0006_compteetudiant_niveau_etude_alter_message_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compteetudiant',
            name='adresse_mail',
            field=models.EmailField(max_length=254, validators=[PP.models.Validate_email_adress]),
        ),
    ]
