# Generated by Django 6.0.2 on 2026-04-03 16:14

import PP.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0007_alter_compteetudiant_adresse_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compteadmin',
            name='adresse_mail',
            field=models.EmailField(max_length=254, validators=[PP.models.Validate_email_adress]),
        ),
        migrations.AlterField(
            model_name='compteetudiant',
            name='matricule',
            field=models.IntegerField(unique=True),
        ),
    ]
