# Generated by Django 6.0.2 on 2026-04-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0008_alter_compteadmin_adresse_mail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='besoin',
            name='participants',
        ),
        migrations.AddField(
            model_name='besoin',
            name='file_path',
            field=models.FileField(null=True, upload_to='files/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='besoin',
            name='justification',
            field=models.CharField(default='meow', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='besoin',
            name='projet_concerne',
            field=models.CharField(default='meow', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='besoin',
            name='typeDeBesoin',
            field=models.CharField(choices=[('MATERIEL', 'Materiel'), ('BUDGET', 'Budget'), ('ENCADREMENT', 'Encadrement'), ('LABORATOIRE', 'Laboratoire'), ('SUPPORT TECHNIQUE', 'Support Technique'), ('FORMATION', 'Formation'), ('NETWORKING', 'Networking')], default='MATERIEL', max_length=20),
        ),
    ]
