# Generated by Django 6.0.2 on 2026-04-19 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0009_remove_besoin_participants_besoin_file_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='besoin',
            name='participant',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='PP.compteetudiant'),
            preserve_default=False,
        ),
    ]
