# Generated by Django 6.0.2 on 2026-04-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0010_besoin_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='besoin',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name=''),
        ),
    ]
