# Generated by Django 6.0.2 on 2026-04-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0011_alter_besoin_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='domaine',
            field=models.CharField(choices=[('Technologie et sante', 'Technologie Et Sante'), ('Technologie et finances', 'Technologie Et Finances'), ('Technologie et environement', 'Technologie Et Environement'), ('E-commerce', 'E Commerce'), ('Technologie et agriculture', 'Technologie Et Agriculture'), ('Autre', 'Autre')], default='Autre', max_length=30),
        ),
        migrations.AddField(
            model_name='projet',
            name='probleme_resolu',
            field=models.CharField(default='Autre', max_length=200),
            preserve_default=False,
        ),
    ]
