# Generated by Django 6.0.2 on 2026-04-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0012_projet_domaine_projet_probleme_resolu'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='objectif',
            field=models.CharField(default='meow', max_length=200),
            preserve_default=False,
        ),
    ]
