# Generated by Django 6.0.2 on 2026-04-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0013_projet_objectif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='domaine',
            field=models.CharField(choices=[('Technologie et sante', 'Technologie et sante'), ('Technologie et finances', 'Technologie et finances'), ('Technologie et environement', 'Technologie et environement'), ('E-commerce', 'E-commerce'), ('Technologie et agriculture', 'Technologie et agriculture'), ('Autre', 'Autre')], default='Autre', max_length=30),
        ),
    ]
