# Generated by Django 6.0.2 on 2026-04-20 08:11

import PP.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0014_alter_projet_domaine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compteetudiant',
            name='matricule',
            field=models.IntegerField(unique=True, validators=[PP.models.Validate_matricule]),
        ),
        migrations.AlterField(
            model_name='compteetudiant',
            name='niveau_etude',
            field=models.CharField(choices=[('1CP', '1CP'), ('2CP', '2CP'), ('1CS', '1CS'), ('2CS', '2CS'), ('3CS', '3CS')], default='1CP', max_length=5),
        ),
        migrations.AlterField(
            model_name='compteetudiant',
            name='telephone',
            field=models.IntegerField(validators=[PP.models.Validate_telephone]),
        ),
    ]
