# Generated by Django 6.0.2 on 2026-04-20 08:49

import PP.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0015_alter_compteetudiant_matricule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='besoin',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='files/', validators=[PP.models.Validate_fichier], verbose_name=''),
        ),
        migrations.AlterField(
            model_name='projet',
            name='file_path',
            field=models.FileField(upload_to='files/', validators=[PP.models.Validate_fichier], verbose_name=''),
        ),
    ]
