# Generated by Django 6.0.2 on 2026-04-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0016_alter_besoin_file_path_alter_projet_file_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('objet', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
    ]
