# Generated by Django 6.0.2 on 2026-04-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0017_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='vu',
            field=models.BooleanField(default=False),
        ),
    ]
