# Generated by Django 6.0.2 on 2026-04-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0018_message_vu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='besoin',
            name='typeDeBesoin',
            field=models.CharField(choices=[('Materiel', 'Materiel'), ('Budget', 'Budget'), ('Encadrement', 'Encadrement'), ('Laboratoire', 'Laboratoire'), ('Support Technique', 'Support Technique'), ('Formation', 'Formation'), ('Networking', 'Networking')], default='MATERIEL', max_length=20),
        ),
    ]
