# Generated by Django 6.0.2 on 2026-04-22 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0019_alter_besoin_typedebesoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PP.besoin'),
        ),
        migrations.AlterField(
            model_name='message',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PP.projet'),
        ),
    ]
